FORMAT: 1A
HOST: https://api.xilnex.com/

# Core Data API V1 - Apps
## Scope and Concepts
Web bytes provides a complete API accessible via HTTPS. This API is the best 
way to intergrate website, e-commerce, server, mobile written in any programming 
language such as JavaScript, Ruby, Swift, Object-C. C#, Java, php, etc.

## Setup for REST API
For using this API you need send authenticated HTTP requests. Exists several 
way to do this:
* Send a HTTPS header with include `Token: {api_token}` and `Dkey: {Dkey}`
, where `{api_token}` is your API token and `{dkey}` is your private key
![name](https://s15.postimg.org/oagoiyr7f/Screenshot_1.png)


Your API token and Dkey you can request from our comapny **api@webbytes.com.my**
by providing below
information in your email
* Company Name:
* Name:
* Purpose of the API:
    * Purpose:
    * Request action: `Read, Write, Update, Delete`
* Super admin email address:
* Api e-mail address :
* Api e-mail password : 

API e-mail address and password `You need to create a user on xilnex application, and
specific for API purpose only`

## Basic Usage
### HTTPS
* All endpoints are available over HTTPS only.

### Allowed HTTPs requests:
* `POST` - To create resource
* `PUT` - To update resource
* `GET` - Get a resource or list of resources
* `DELETE` - To delete resource

### Description Of Usual Server Responses:
* 200 `ok` - the request was successful
    * `ok` 
        * `true` mean success to process 
    * `status` - status of process
        * `SuccessQuery`
        * `SuccessInsert`
        * `SuccessDelete`
        * `SuccessUpdate`
    * `warning`
        * null
    * `error`
        * null
    * `data` - Json data response from Api
        * Object
    * `timestamp`
* 400 `Bad Request` - the request could not be understood or was missing required parameters.
    * `ok` 
        * `false` mean failed to process
    * `status` - status of process
    * `warning` - warning message return from server
    * `timestamp`
* 401 `Unauthorized` - authentication failed or user doesn't have 
permissions for requested operation.
* 500 `Internal server error` - server error

#Group Sync
Sync api is use for intergration with your preferce e-commerce, like sync stock, sales, client etc.
one times the api will only return you 4k row of data only, then will need to make another call to 
get the rest of data. You will need to keep the last Timestamp and pass to us in your another call,
so api will return next group of data. 

Example
1. First time call to sync API
![name](https://s1.postimg.org/tdz2j7kxr/Untitled.png)

2. Return result from sync API, you will need to keep the lastTimestamp for next call
![name](https://s18.postimg.org/buividotl/Untitled.png)

3. Call APi with the lastTimestamp receive from last call
![name](https://s10.postimg.org/jxz53v47d/Untitled.png)

4. repreat the step until receive zero row data from API
![name](https://s3.postimg.org/frhn90mlv/Untitled.png)

## Group Client Sync

### /apps/v1/sync/clients

#### GET

This is api use to synced clients with your preferce e-commerce, api will return first 4k row of data.

+ Request

    + Headers

            Accept: application/json
            Header: {header}
            Token: {token}

    + Body
    
+ Response 200 (application/json)

    {
    "ok": true,
    "status": "SuccessQuery",
    "warning": null,
    "error": null,
    "data": {
        "lastTimestamp": "0x00000000786166CC",
        "client": null,
        "clients": [
            {
                "id": 9220145,
                "alternateLookup": "045454",
                "priceScheme": "-1",
                "terms": 0,
                "creditLimit": 0,
                "billingAddress": "",
                "shippingAddress": "",
                "billing": {
                    "street": "",
                    "city": "",
                    "state": "",
                    "zipcode": "",
                    "country": ""
                },
                "shipping": {
                    "street": "",
                    "city": "",
                    "state": "",
                    "zipcode": "",
                    "country": ""
                },
                "name": "Abu",
                "code": "",
                "title": "",
                "email": "",
                "type": "Member",
                "group": "",
                "registrationCode": "4545454",
                "gender": "female",
                "dob": "1995-01-13T00:00:00.000Z",
                "ic": "",
                "nationality": null,
                "createdBy": "01122455",
                "mobile": null,
                "office": null,
                "fax": null,
                "phone": null,
                "alternateContact": null,
                "alternatePhone": null,
                "category": null,
                "firstName": null,
                "lastName": null,
                "expiryDate": "2017-04-24T00:00:00.000Z",
                "pointValue": 94.85
            },
            {
                "id": 4556545,
                "alternateLookup": "5454554",
                "priceScheme": "0",
                "terms": 0,
                "creditLimit": 0,
                "billingAddress": "",
                "shippingAddress": "",
                "billing": {
                    "street": "",
                    "city": "",
                    "state": "",
                    "zipcode": "",
                    "country": ""
                },
                "shipping": {
                    "street": "",
                    "city": "",
                    "state": "",
                    "zipcode": "",
                    "country": ""
                },
                "name": "Ah chin",
                "code": "45sd416fd6d",
                "title": "",
                "email": "asdad56@gmail.com,my",
                "type": "Member",
                "group": "Member",
                "registrationCode": "654sd6f45s",
                "gender": "F",
                "dob": "1569-03-02T00:00:00.000Z",
                "ic": null,
                "nationality": null,
                "createdBy": null,
                "mobile": null,
                "office": null,
                "fax": null,
                "phone": null,
                "alternateContact": null,
                "alternatePhone": null,
                "category": null,
                "firstName": null,
                "lastName": null,
                "expiryDate": "2017-06-13T00:00:00.000Z",
                "pointValue": 526456.07
            }
        }
    }

### /apps/v1/sync/clients?startTimeStamp={lastTimestamp}

#### GET

This is api use to synced clients with your preferce e-commerce, api will return you next group of data.

+ Request

    + Headers

            Accept: application/json
            Header: {header}
            Token: {token}

    + Body
    
+ Response 200 (application/json)

    {
    "ok": true,
    "status": "SuccessQuery",
    "warning": null,
    "error": null,
    "data": {
        "lastTimestamp": "0x00000000786166CC",
        "client": null,
        "clients": [
            {
                "id": 9220145,
                "alternateLookup": "045454",
                "priceScheme": "-1",
                "terms": 0,
                "creditLimit": 0,
                "billingAddress": "",
                "shippingAddress": "",
                "billing": {
                    "street": "",
                    "city": "",
                    "state": "",
                    "zipcode": "",
                    "country": ""
                },
                "shipping": {
                    "street": "",
                    "city": "",
                    "state": "",
                    "zipcode": "",
                    "country": ""
                },
                "name": "Abu",
                "code": "",
                "title": "",
                "email": "",
                "type": "Member",
                "group": "",
                "registrationCode": "4545454",
                "gender": "female",
                "dob": "1995-01-13T00:00:00.000Z",
                "ic": "",
                "nationality": null,
                "createdBy": "01122455",
                "mobile": null,
                "office": null,
                "fax": null,
                "phone": null,
                "alternateContact": null,
                "alternatePhone": null,
                "category": null,
                "firstName": null,
                "lastName": null,
                "expiryDate": "2017-04-24T00:00:00.000Z",
                "pointValue": 94.85
            },
            {
                "id": 4556545,
                "alternateLookup": "5454554",
                "priceScheme": "0",
                "terms": 0,
                "creditLimit": 0,
                "billingAddress": "",
                "shippingAddress": "",
                "billing": {
                    "street": "",
                    "city": "",
                    "state": "",
                    "zipcode": "",
                    "country": ""
                },
                "shipping": {
                    "street": "",
                    "city": "",
                    "state": "",
                    "zipcode": "",
                    "country": ""
                },
                "name": "Ah chin",
                "code": "45sd416fd6d",
                "title": "",
                "email": "asdad56@gmail.com,my",
                "type": "Member",
                "group": "Member",
                "registrationCode": "654sd6f45s",
                "gender": "F",
                "dob": "1569-03-02T00:00:00.000Z",
                "ic": null,
                "nationality": null,
                "createdBy": null,
                "mobile": null,
                "office": null,
                "fax": null,
                "phone": null,
                "alternateContact": null,
                "alternatePhone": null,
                "category": null,
                "firstName": null,
                "lastName": null,
                "expiryDate": "2017-06-13T00:00:00.000Z",
                "pointValue": 526456.07
            }
        }
    }
    
### /apps/v1/sync/clients?startTimeStamp={lastTimestamp}&endTimeStamp={timestamp}

#### GET

This is api use to synced clients with your preferce e-commerce, api will return you the data between the 
start time stamp and end time stamp

+ Request

    + Headers

            Accept: application/json
            Header: {header}
            Token: {token}

    + Body
    
+ Response 200 (application/json)

    {
    "ok": true,
    "status": "SuccessQuery",
    "warning": null,
    "error": null,
    "data": {
        "lastTimestamp": "0x00000000786166CC",
        "client": null,
        "clients": [
            {
                "id": 9220145,
                "alternateLookup": "045454",
                "priceScheme": "-1",
                "terms": 0,
                "creditLimit": 0,
                "billingAddress": "",
                "shippingAddress": "",
                "billing": {
                    "street": "",
                    "city": "",
                    "state": "",
                    "zipcode": "",
                    "country": ""
                },
                "shipping": {
                    "street": "",
                    "city": "",
                    "state": "",
                    "zipcode": "",
                    "country": ""
                },
                "name": "Abu",
                "code": "",
                "title": "",
                "email": "",
                "type": "Member",
                "group": "",
                "registrationCode": "4545454",
                "gender": "female",
                "dob": "1995-01-13T00:00:00.000Z",
                "ic": "",
                "nationality": null,
                "createdBy": "01122455",
                "mobile": null,
                "office": null,
                "fax": null,
                "phone": null,
                "alternateContact": null,
                "alternatePhone": null,
                "category": null,
                "firstName": null,
                "lastName": null,
                "expiryDate": "2017-04-24T00:00:00.000Z",
                "pointValue": 94.85
            },
            {
                "id": 4556545,
                "alternateLookup": "5454554",
                "priceScheme": "0",
                "terms": 0,
                "creditLimit": 0,
                "billingAddress": "",
                "shippingAddress": "",
                "billing": {
                    "street": "",
                    "city": "",
                    "state": "",
                    "zipcode": "",
                    "country": ""
                },
                "shipping": {
                    "street": "",
                    "city": "",
                    "state": "",
                    "zipcode": "",
                    "country": ""
                },
                "name": "Ah chin",
                "code": "45sd416fd6d",
                "title": "",
                "email": "asdad56@gmail.com,my",
                "type": "Member",
                "group": "Member",
                "registrationCode": "654sd6f45s",
                "gender": "F",
                "dob": "1569-03-02T00:00:00.000Z",
                "ic": null,
                "nationality": null,
                "createdBy": null,
                "mobile": null,
                "office": null,
                "fax": null,
                "phone": null,
                "alternateContact": null,
                "alternatePhone": null,
                "category": null,
                "firstName": null,
                "lastName": null,
                "expiryDate": "2017-06-13T00:00:00.000Z",
                "pointValue": 526456.07
            }
        }
    }
    
    ## Group Client Sync

### /apps/v1/sync/Items

#### GET

This is api use to synced Items with your preferce e-commerce, api will return first 4k row of data.

+ Request

    + Headers

            Accept: application/json
            Header: {header}
            Token: {token}

    + Body
    
+ Response 200 (application/json)

    {  
       "ok":true,
       "status":"SuccessQuery",
       "warning":null,
       "error":null,
       "data":{  
          "item":null,
          "items":[  
             {  
                "id":988013128,
                "itemCode":"988013128",
                "itemName":"TestItemName  task:0counter0",
                "itemType":"",
                "itemModel":"",
                "alternateLookup":"",
                "description":"",
                "brand":"",
                "category":"",
                "departmentCode":"",
                "departmentName":null,
                "vendorCode":"",
                "cost":0,
                "suggestedPrice":0,
                "salesPrice":0,
                "employeePrice":0,
                "wholesalesPrice":0,
                "customPrice":0,
                "webPrice":0,
                "webDealerPrice":0,
                "attribute":"",
                "size":"",
                "stockType":null,
                "matrixXGroup":null,
                "matrixYGroup":null,
                "groupName":"",
                "promotionGroup":"",
                "customField1":"",
                "customField2":"",
                "customField3":"",
                "customField4":"",
                "customField5":"",
                "customField6":"",
                "customField7":"",
                "customField8":"",
                "customField9":"",
                "customField10":"",
                "customField11":"",
                "customField12":"",
                "customField13":"",
                "customField14":"",
                "customField15":"",
                "gstRate":0,
                "gstSupplyCode":"",
                "gstPurchaseCode":"",
                "image":null,
                "sellingPrice":0,
                "productMatrixInfo":null,
                "uniqueItemInfo":null,
                "subItems":null
             }
          ],
          "lastTimestamp":""
       },
       "timestamp":1505969472
    }

### /apps/v1/sync/Items?startTimeStamp={lastTimestamp}

#### GET

This is api use to synced Items with your preferce e-commerce, api will return you next group of data.

+ Request

    + Headers

            Accept: application/json
            Header: {header}
            Token: {token}

    + Body
    
+ Response 200 (application/json)

    {  
       "ok":true,
       "status":"SuccessQuery",
       "warning":null,
       "error":null,
       "data":{  
          "item":null,
          "items":[  
             {  
                "id":988013128,
                "itemCode":"988013128",
                "itemName":"TestItemName  task:0counter0",
                "itemType":"",
                "itemModel":"",
                "alternateLookup":"",
                "description":"",
                "brand":"",
                "category":"",
                "departmentCode":"",
                "departmentName":null,
                "vendorCode":"",
                "cost":0,
                "suggestedPrice":0,
                "salesPrice":0,
                "employeePrice":0,
                "wholesalesPrice":0,
                "customPrice":0,
                "webPrice":0,
                "webDealerPrice":0,
                "attribute":"",
                "size":"",
                "stockType":null,
                "matrixXGroup":null,
                "matrixYGroup":null,
                "groupName":"",
                "promotionGroup":"",
                "customField1":"",
                "customField2":"",
                "customField3":"",
                "customField4":"",
                "customField5":"",
                "customField6":"",
                "customField7":"",
                "customField8":"",
                "customField9":"",
                "customField10":"",
                "customField11":"",
                "customField12":"",
                "customField13":"",
                "customField14":"",
                "customField15":"",
                "gstRate":0,
                "gstSupplyCode":"",
                "gstPurchaseCode":"",
                "image":null,
                "sellingPrice":0,
                "productMatrixInfo":null,
                "uniqueItemInfo":null,
                "subItems":null
             }
          ],
          "lastTimestamp":""
       },
       "timestamp":1505969472
    }
    
### /apps/v1/sync/Items?startTimeStamp={lastTimestamp}&endTimeStamp={timestamp}

#### GET

This is api use to synced Items with your preferce e-commerce, api will return you the data between the 
start time stamp and end time stamp

+ Request

    + Headers

            Accept: application/json
            Header: {header}
            Token: {token}

    + Body
    
+ Response 200 (application/json)

    {  
       "ok":true,
       "status":"SuccessQuery",
       "warning":null,
       "error":null,
       "data":{  
          "item":null,
          "items":[  
             {  
                "id":988013128,
                "itemCode":"988013128",
                "itemName":"TestItemName  task:0counter0",
                "itemType":"",
                "itemModel":"",
                "alternateLookup":"",
                "description":"",
                "brand":"",
                "category":"",
                "departmentCode":"",
                "departmentName":null,
                "vendorCode":"",
                "cost":0,
                "suggestedPrice":0,
                "salesPrice":0,
                "employeePrice":0,
                "wholesalesPrice":0,
                "customPrice":0,
                "webPrice":0,
                "webDealerPrice":0,
                "attribute":"",
                "size":"",
                "stockType":null,
                "matrixXGroup":null,
                "matrixYGroup":null,
                "groupName":"",
                "promotionGroup":"",
                "customField1":"",
                "customField2":"",
                "customField3":"",
                "customField4":"",
                "customField5":"",
                "customField6":"",
                "customField7":"",
                "customField8":"",
                "customField9":"",
                "customField10":"",
                "customField11":"",
                "customField12":"",
                "customField13":"",
                "customField14":"",
                "customField15":"",
                "gstRate":0,
                "gstSupplyCode":"",
                "gstPurchaseCode":"",
                "image":null,
                "sellingPrice":0,
                "productMatrixInfo":null,
                "uniqueItemInfo":null,
                "subItems":null
             }
          ],
          "lastTimestamp":""
       },
       "timestamp":1505969472
    }
    
## Group Stock Sync

### /apps/v1/sync/stock

#### GET

This is api use to synced stock with your preferce e-commerce, api will return first 4k row of data.

+ Request

    + Headers

            Accept: application/json
            Header: {header}
            Token: {token}

    + Body
    
+ Response 200 (application/json)

    {
    "ok": true,
    "status": "SuccessQuery",
    "warning": null,
    "error": null,
    "data": {
        "lastTimestamp": "0x00000000772C2D62",
        "stocks": [
            {
                "itemCode": "56465as4d",
                "outlet": "sds-sd",
                "availableQuantity": 0,
                "onhandQuantity": 0
            },
            {
                "itemCode": "wewe",
                "outlet": "wew-wew",
                "availableQuantity": 0,
                "onhandQuantity": 0
            },
            {
                "itemCode": "qweeqw",
                "outlet": "asdad-3242",
                "availableQuantity": 0,
                "onhandQuantity": 0
            },
            {
                "itemCode": "234wfer",
                "outlet": "234242df-2342d",
                "availableQuantity": 0,
                "onhandQuantity": 0
            }
        }
    }

### /apps/v1/sync/stock?startTimeStamp={lastTimestamp}

#### GET

This is api use to synced stock with your preferce e-commerce, api will return you next group of data.

+ Request

    + Headers

            Accept: application/json
            Header: {header}
            Token: {token}

    + Body
    
+ Response 200 (application/json)

    {
    "ok": true,
    "status": "SuccessQuery",
    "warning": null,
    "error": null,
    "data": {
        "lastTimestamp": "0x00000000772CBC3F",
        "stocks": [
            {
                "itemCode": "e1d12e
                "outlet": "1231312-sdfs",
                "availableQuantity": 0,
                "onhandQuantity": 0
            },
            {
                "itemCode": "f2
                "outlet": "asdad-12313",
                "availableQuantity": 0,
                "onhandQuantity": 0
            },
            {
                "itemCode": "asdad",
                "outlet": "112313-asdad",
                "availableQuantity": 0,
                "onhandQuantity": 0
            }
        }
    }
    
### /apps/v1/sync/stock?startTimeStamp={lastTimestamp}&endTimeStamp={timestamp}

#### GET

This is api use to synced stock with your preferce e-commerce, api will return you the data between the 
start time stamp and end time stamp

+ Request

    + Headers

            Accept: application/json
            Header: {header}
            Token: {token}

    + Body
    
+ Response 200 (application/json)

    {
    "ok": true,
    "status": "SuccessQuery",
    "warning": null,
    "error": null,
    "data": {
        "lastTimestamp": "0x00000000772CBC3F",
        "stocks": [
            {
                "itemCode": "asdad12",
                "outlet": "1231sd",
                "availableQuantity": 0,
                "onhandQuantity": 0
            },
            {
                "itemCode": "sdasda
                "outlet": "12313-asdas",
                "availableQuantity": 0,
                "onhandQuantity": 0
            },
            {
                "itemCode": "adcsdas2",
                "outlet": "awe-123asdfd",
                "availableQuantity": 0,
                "onhandQuantity": 0
            }
        }
    }